api_key: ''  # 请替换为您的 Alpha Vantage API 密钥
fred_api_key: '' # 请替换为您的 FRED API 密钥
tickers:
  - DIA
  - IWM
  - QQQ
  - SPY
  - VXX
  - XLB
  - XLE
  - XLF
  - XLI
  - XLK
  - XLP
  - XLRE
  - XLU
  - XLV
  - XLY
start_date: '2010-01-01'
train_end_date: '2019-12-31'
max_lag: 10
lstm:
  lookback: 20
  epochs: 100
  hidden_dim: 50
  num_layers: 1
  learning_rate: 0.001
  validation_ratio: 0.1 
  early_stopping_patience: 20